(defun c:slabdetails ()
  (setvar "cmdecho" 0)
  (setq restoreosmode (getvar "osmode"))
  (setvar "INSUNITS" 4)
  (setq unit (getstring "Is the drawings in Foot & inches system?(y/n)"))
  (setq count 0)
  (setq c (getint "Please enter the cover for the steel"))
  (while (eq count 0)
    (setq pt1 (getpoint "Select the top-left corner of the slab"))
    (setq pt2 (getpoint "Select the top-right corner of the slab"))
    (setq pt3 (getpoint "Select the bottom-left corner of the slab"))
    (setq pt4 (getpoint "Select the bottom-right corner of the slab"))
      (command "line" (mapcar '+ pt1 (list (/ (distance pt1 pt2) 2) (- c) 0))
	       (mapcar '+ pt1 (list (/ (distance pt1 pt2) 2) (- c) 0) (list 18 0 0))
	       "")
      (command "line" (mapcar '+ pt1 (list (/ (distance pt1 pt2) 2) (- c) 0))
	       (mapcar '+ pt3 (list (/ (distance pt1 pt2) 2) c 0))
	       "")
      (command "line" (mapcar '+ pt3 (list (/ (distance pt1 pt2) 2) c 0))
	       (mapcar '+ pt3 (list (/ (distance pt1 pt2) 2) c 0) (list 18 0 0))
	       "") 
    (command "line" (mapcar '- pt1 (list (- c) (/ (distance pt1 pt3) 2) 0))
	       (mapcar '- pt1 (list (- c) (/ (distance pt1 pt3) 2) 0) (list 0 18 0))
	       "")
      (command "line" (mapcar '- pt1 (list (- c) (/ (distance pt1 pt3) 2) 0))
	       (mapcar '- pt2 (list (- c) (/ (distance pt1 pt3) 2) 0))
	       "")
      (command "line" (mapcar '+ pt2 (list (- c) (/ (distance pt1 pt3) 2) 0))
	       (mapcar '+ pt2 (list (- c) (/ (distance pt1 pt3) 2) 0) (list 0 18 0))
	       "")
    (setq finish (getstring "Are you done? (y/n)"))
    (if (or (eq finish "y") (eq finish "Y"))
      (setq count 1)
      (setq count 0)
      )
    )
  )
    
  
  
  
  